import "@/app/globals.css";
import "@/app/theme-config.css";
import "@radix-ui/themes/styles.css";
import { Anton, Roboto, Special_Elite } from "next/font/google";

export const metadata = {
	title: "Start Issue Tracker",
	description: "Generated by Next.js",
};

export const specialElite = Special_Elite({
	subsets: ["latin"],
	weight: "400", // Correct syntax for specifying weights
	variable: "--font-specialElite",
});

export const anton = Anton({
	subsets: ["latin"],
	weight: "400", // Correct syntax for specifying weights
	variable: "--font-anton",
});

export const roboto = Roboto({
	subsets: ["latin"],
	weight: "400", // Correct syntax for specifying weights
	variable: "--font-roboto",
});

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body
				className={`${specialElite.variable} ${anton.variable} ${roboto.variable}`}
			>
				{children}
			</body>
		</html>
	);
}
